### ISSUE TITLE
Multiple pages issue

### ISSUE THREAD

**Issue by onebeat** [RafaelCecchin/cups-printer#4]
Hello, i have installed your script and works great when print single page, but multiple pages it cuts header and footer of document ? 

Do you have idea why does it happen ?

**Comment by RafaelCecchin** [comment]
Hello.
Are you using a library like "dompdf"?
If so, when you run "$pdf->stream(...)" does the PDF appear ok?
Do this to debug. If you are viewing the PDF correctly in your browser, it may be that your printer configuration in CUPS is not correct.
